// AUTO-GENERATED by xtask codegen from tools/schemas/cli.toml - do not edit
#![allow(clippy::all, dead_code)]

#[rustfmt::skip]
pub const ROOT_HELP_TEMPLATE: &str = "{about-with-newline}\n{usage-heading} {usage}\n\nSession commands:\n  run        Run an agent session\n  create     Create a session, label, or other resource\n  get        Show sessions and other resources\n  delete     Delete sessions and other resources\n  label      Update labels on a resource\n  mail       Send mail to an agent\n  nudge      Nudge an agent\n  capture    Capture session output\n  logs       Tail session logs\n  wait       Wait for a session condition\n  mcp        Run lilo as an MCP server\n\nSubstrate operator commands:\n  runtime    Raw runtime operator namespace. runtime spawn never creates session records.\n  session    Session substrate operator namespace\n  identity   Identity substrate operator namespace\n\nDiagnostics:\n  doctor     Inspect local lilo health\n\nDaemon lifecycle:\n  daemon     Manage the local lilo daemon process\n\nOptions:\n{options}{after-help}\n";

#[rustfmt::skip]
pub const RUN_ABOUT: &str = "Run an agent session";
#[rustfmt::skip]
pub const CREATE_ABOUT: &str = "Create a session, label, or other resource";
#[rustfmt::skip]
pub const GET_ABOUT: &str = "Show sessions and other resources";
#[rustfmt::skip]
pub const DELETE_ABOUT: &str = "Delete sessions and other resources";
#[rustfmt::skip]
pub const LABEL_ABOUT: &str = "Update labels on a resource";
#[rustfmt::skip]
pub const MAIL_ABOUT: &str = "Send mail to an agent";
#[rustfmt::skip]
pub const NUDGE_ABOUT: &str = "Nudge an agent";
#[rustfmt::skip]
pub const CAPTURE_ABOUT: &str = "Capture session output";
#[rustfmt::skip]
pub const LOGS_ABOUT: &str = "Tail session logs";
#[rustfmt::skip]
pub const WAIT_ABOUT: &str = "Wait for a session condition";
#[rustfmt::skip]
pub const MCP_ABOUT: &str = "Run lilo as an MCP server";
#[rustfmt::skip]
pub const RUNTIME_ABOUT: &str = "Raw runtime operator namespace. runtime spawn never creates session records.";
#[rustfmt::skip]
pub const SESSION_ABOUT: &str = "Session substrate operator namespace";
#[rustfmt::skip]
pub const IDENTITY_ABOUT: &str = "Identity substrate operator namespace";
#[rustfmt::skip]
pub const DOCTOR_ABOUT: &str = "Inspect local lilo health";
#[rustfmt::skip]
pub const DAEMON_ABOUT: &str = "Manage the local lilo daemon process";
#[rustfmt::skip]
pub const RUNTIME_SHIM_ABOUT: &str = "Run the hidden runtime shim";
