// AUTO-GENERATED by xtask codegen from tools/schemas/cli.toml - do not edit
#![allow(clippy::all, dead_code)]

#[rustfmt::skip]
pub const CLI_SURFACE_JSON: &str = r#"{
  "groups": [
    {
      "commands": [
        {
          "about": "Run an agent session",
          "const_name": "RUN",
          "group": "session",
          "hidden": null,
          "name": "run"
        },
        {
          "about": "Create a session, label, or other resource",
          "const_name": "CREATE",
          "group": "session",
          "hidden": null,
          "name": "create"
        },
        {
          "about": "Show sessions and other resources",
          "const_name": "GET",
          "group": "session",
          "hidden": null,
          "name": "get"
        },
        {
          "about": "Delete sessions and other resources",
          "const_name": "DELETE",
          "group": "session",
          "hidden": null,
          "name": "delete"
        },
        {
          "about": "Update labels on a resource",
          "const_name": "LABEL",
          "group": "session",
          "hidden": null,
          "name": "label"
        },
        {
          "about": "Send mail to an agent",
          "const_name": "MAIL",
          "group": "session",
          "hidden": null,
          "name": "mail"
        },
        {
          "about": "Nudge an agent",
          "const_name": "NUDGE",
          "group": "session",
          "hidden": null,
          "name": "nudge"
        },
        {
          "about": "Capture session output",
          "const_name": "CAPTURE",
          "group": "session",
          "hidden": null,
          "name": "capture"
        },
        {
          "about": "Tail session logs",
          "const_name": "LOGS",
          "group": "session",
          "hidden": null,
          "name": "logs"
        },
        {
          "about": "Wait for a session condition",
          "const_name": "WAIT",
          "group": "session",
          "hidden": null,
          "name": "wait"
        },
        {
          "about": "Run lilo as an MCP server",
          "const_name": "MCP",
          "group": "session",
          "hidden": null,
          "name": "mcp"
        }
      ],
      "heading": "Session commands",
      "id": "session"
    },
    {
      "commands": [
        {
          "about": "Raw runtime operator namespace. runtime spawn never creates session records.",
          "const_name": "RUNTIME",
          "group": "operator",
          "hidden": null,
          "name": "runtime"
        },
        {
          "about": "Session substrate operator namespace",
          "const_name": "SESSION",
          "group": "operator",
          "hidden": null,
          "name": "session"
        },
        {
          "about": "Identity substrate operator namespace",
          "const_name": "IDENTITY",
          "group": "operator",
          "hidden": null,
          "name": "identity"
        }
      ],
      "heading": "Substrate operator commands",
      "id": "operator"
    },
    {
      "commands": [
        {
          "about": "Inspect local lilo health",
          "const_name": "DOCTOR",
          "group": "diagnostics",
          "hidden": null,
          "name": "doctor"
        }
      ],
      "heading": "Diagnostics",
      "id": "diagnostics"
    },
    {
      "commands": [
        {
          "about": "Manage the local lilo daemon process",
          "const_name": "DAEMON",
          "group": "daemon",
          "hidden": null,
          "name": "daemon"
        }
      ],
      "heading": "Daemon lifecycle",
      "id": "daemon"
    }
  ],
  "hidden_commands": [
    {
      "about": "Run the hidden runtime shim",
      "const_name": "RUNTIME_SHIM",
      "group": null,
      "hidden": true,
      "name": "__shim"
    }
  ],
  "surface": {
    "about": "Local-first Little Organs control plane",
    "binary": "lilo",
    "display_name": "littleorgans"
  }
}"#;

#[rustfmt::skip]
pub const MCP_SCHEMA_JSON: &str = r#"{
  "description": "Local-first Little Organs control plane",
  "input_schema": {
    "properties": {
      "command": {
        "enum": [
          "run",
          "create",
          "get",
          "delete",
          "label",
          "mail",
          "nudge",
          "capture",
          "logs",
          "wait",
          "mcp",
          "runtime",
          "session",
          "identity",
          "doctor",
          "daemon"
        ],
        "type": "string"
      }
    },
    "required": [
      "command"
    ],
    "type": "object"
  },
  "name": "lilo"
}"#;
